//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adsmap.EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity : IEntityObjectState
    {
        public EntityObjectState ObjectState { get; set; }
        public int Id { get; set; }
        public int TerminalItemId { get; set; }
        public int TerminalComponentId { get; set; }
        public float LastValue { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual TerminalComponent TerminalComponent { get; set; }
        public virtual TerminalItem TerminalItem { get; set; }
    }
}
