//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adsmap.EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula : IEntityObjectState
    {
        public EntityObjectState ObjectState { get; set; }
        public Formula()
        {
            this.Roles = new HashSet<Role>();
            this.Parameters = new HashSet<Parameter>();
        }
    
        public int Id { get; set; }
        public string RegularExpression { get; set; }
        public bool IsServerSide { get; set; }
    
         
        public virtual ICollection<Role> Roles { get; set; }
         
        public virtual ICollection<Parameter> Parameters { get; set; }
    }
}
