//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adsmap.EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacture : IEntityObjectState
    {
        public EntityObjectState ObjectState { get; set; }
        public Manufacture()
        {
            this.Components = new HashSet<Component>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
    
         
        public virtual ICollection<Component> Components { get; set; }
    }
}
