//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adsmap.EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType : IEntityObjectState
    {
        public EntityObjectState ObjectState { get; set; }

        public UnitType()
        {
            this.UnitItems = new HashSet<UnitItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Capacity { get; set; }
        public string Details { get; set; }
    
         
        public virtual ICollection<UnitItem> UnitItems { get; set; }
    }
}
